### ISSUE TITLE
Add support to context

### ISSUE THREAD

**Issue by diegobernardes** [globalsign/mgo#109]
It should be nice to have context support. This is a long time requested feature on mgo.

**Comment by domodwyer** [comment]
Hi @diegobernardes 

I fully agree, it would be great! It would take a huge rewrite of mgo and would be unlikely to be backwards compatible so it's not on the list at the moment - saying that, we're happy to accept a PR! There might be a few functions where it makes sense as a big gain initial effort, stuff like the bulk processing operations, etc.

Something to think about, thanks!
Dom
