### ISSUE TITLE
dbtest without mongod

### ISSUE THREAD

**Issue by cyberhck** [globalsign/mgo#124]
So I use docker for mongo but I still build and run go in host machine, is there a way to do testing without actually installing mongod?

**Comment by szank** [comment]
Hi,
Sorry for the late reply. 
Currently, mgo doesn't support such scenario. 

It shouldn't be too hard to create a `DBServer` interface and switch concrete implementations based on flags parsed from TestMain(). 
PRs are most welcome! 
I am closing the issue, now, but we would be happy to review any PRs adding support for this. Or Atlas ;).
