### ISSUE TITLE
where is  mgo doc file？

### ISSUE THREAD

**Issue by fancyecommerce** [globalsign/mgo#126]
where is  mgo doc file？

how can  i use mgo?

**Comment by spectralsun** [comment]
+1 where are the docs?

**Comment by okabbas** [comment]
+1 Please give me the documentation I also need.

**Comment by szank** [comment]
Hi, 
The mgo documentation can be found on godoc: https://godoc.org/github.com/globalsign/mgo, 
as usual for the go packages.

**Comment by carldunham** [comment]
Um, that documentation refers to labix.org, which makes it look like the project hasn't been updated since 2015.
