### ISSUE TITLE
Wrong type of socket

### ISSUE THREAD

**Issue by yudao** [globalsign/mgo#132]
Hi,

I have a program which take some sources (XML, CSV, JSON, ...), parse them and save the formatted format into a mongodb.

Until now, all files was stored without errors.

Unfortunately, today a new source file has been treated (100%) but can't be store due to this error:
```
Error: write tcp 127.0.0.1:55519->127.0.0.1:27017: write: protocol wrong type for socket
```

Do you know what are the possible tracks that can cause this socket error?

Thx a lot.

Yu.

**Comment by szank** [comment]
Hi @yudao 

I had a quick google, and it doesn't seem like a mgo error to me. Are you using BSD-is system by any chance? (Including osx)

There are other reports of this error. What go version are you using?

I'd like to help, but I need more details. It is possible that you might need to raise an issue with go. 
Does it happen often/every time/only once?

**Comment by yudao** [comment]
Hi @szank,

Thx for your quick help.
Yes I'm **using macOS High Sierra (17D102)**.
My go version **go1.10 darwin/amd64**

Do you think that the size of the must be the problem?

Yu.

**Comment by szank** [comment]
I don't really think so. 
You could fire up wireshark and check what is going on the wire though. My best guess it that no data is sent. 

I am going to close this issue, as I don't think I can help much. Please try opening an issue in the go's bug tracker, they might be able to help you. This really doesn't look like an error in mgo code, more like the net package or the osx. 

If you can reproduce it reliably it would be a great help to anyone on go team who would be able to fix this issue. If it is intermittent, you will just need to retry the mgo operation if necessary.
