### ISSUE TITLE
update document problem

### ISSUE THREAD

**Issue by ByLuxury** [globalsign/mgo#138]
When I do something about  mongodb with mgo, It seems that library may be some  problems.that's following the description:
When I update documents ,generally,use update or updateId,updateAll Api,All of this Api, these Api 
 modifies documents documents according to the update documents that offered.it will delete some fields,it only reserves update document fields.it seems  not a good design. sometimes,I want to update some fields  and hope reserve all fields.

**Comment by szank** [comment]
Hi, 

mgo is using the update API provided by MongoDB. The way the update functionality works is identical in all the MongoDB drivers we are aware of. We are not responsible for the design decisions made by MongoDB. If there is a specific scenario that we are not supporting currently, please provide us with a steps to reproduce it and an expected result. 

If you have questions about the way MongoDB update operations work, maybe this will offer some help: 
https://docs.mongodb.com/manual/reference/method/db.collection.update/
https://docs.mongodb.com/manual/reference/operator/update/
 
If you want to modify only selected fields in an existing document, you could use the $set operator: 
https://docs.mongodb.com/manual/reference/operator/update/set/#up._S_set
