### ISSUE TITLE
'big cpu use' problem 

### ISSUE THREAD

**Issue by JeffreyDing11223** [globalsign/mgo#143]
https://github.com/go-mgo/mgo/issues/403
I got the 'big cpu use problem' as like as #403 , because of
`func (c *Client) saltPassword(salt []byte, iterCount int) {`

in the `func (s *Session) acquireSocket(slaveOk bool) (*mongoSocket, error) {`
after `s.cluster().AcquireSocket( `, will go to `s.socketLogin(sock)` , and then happen the above problem , the problem always happen after the program has run 1 or 2 hours

**Comment by JeffreyDing11223** [comment]
I think it is related to this issue
https://github.com/go-mgo/mgo/issues/254
I pulled the newest codes just now , see the problem will happen or not

**Comment by domodwyer** [comment]
Hi @JeffreyDing11223 

This is either due to the bug you mentioned, or can be resolved via the instructions in 403. Either way, we can only help with the latest version of our fork.

Dom
