### ISSUE TITLE
Consider detaching this repository from domodwyer/mgo

### ISSUE THREAD

**Issue by theckman** [globalsign/mgo#172]
You can reach out to the GitHub support team to have them detach forks from the upstream projects, in cases like this where this project is now effectively the canonical upstream project.

This would make some functions of working with this repo easier, as well as get rid of the diff-stats between this repo and `domodwyer/mgo#master` as seen in the root of this project.

Not sure if this is something you want to do, but I think it would be a good step to take.

**Comment by domodwyer** [comment]
Hi @theckman 

I didn't know that, thanks very much!

Dom
