### ISSUE TITLE
Race condition on minPoolSize and maxIdleTimeMS

### ISSUE THREAD

**Issue by bmarguer** [globalsign/mgo#173]
Hello.
It seems to have a race condition (latest tag : efe0945164a7e582241f37ae8983c075f8f2e870)  on "DialWithInfo" when :
- write part :  cluster.minPoolSize is written 
- read part : just before "newCluster" has created the goroutine which launch the synServersLoop (this routine calls syncServersIteration --> spawnSync --> cluster.server --> minPoolSize := cluster.minPoolSize)
I think the minPoolSize and the maxIdleTimeMS should be params of newCluster function like others info attributes ?

**Comment by domodwyer** [comment]
Hi @bmarguer 

This code has been [extensively reworked](https://github.com/globalsign/mgo/pull/161) - would you mind trying the `development` branch and confirming it is still an issue?

Thanks!

Dom

**Comment by domodwyer** [comment]
Hey @bmarguer 

That's great, thanks for opening the issue to check though!

Dom
