### ISSUE TITLE
Array Filters not implemented

### ISSUE THREAD

**Issue by JeremyLoy** [globalsign/mgo#179]
[Related MongoDB Documentation](https://docs.mongodb.com/manual/reference/method/db.collection.update/#update-arrayfilters)

We have a need to update only a subset of an array. This capability exists in MongoDB as an Array Filter, however that functionality doesn't seem to be exposed in this SDK.

`globalsign/mgo/updateOp` would need to be updated. In order to maintain backwards compatibility, new `UpdateX` methods would need to be made as changing the signatures would be required. Alternatively, some sort of builder pattern could be exposed.

**Comment by domodwyer** [comment]
Hi @JeremyLoy 

I'm pretty sure the `$filter` can be part of the selector but don't use it myself - a quick google turned [this](https://stackoverflow.com/questions/37153518/how-to-write-these-mongo-code-in-go) up - does it work for you?

Dom

**Comment by domodwyer** [comment]
Ah sorry, different filter! Looks like you're right, it'll probably need an addition to the API.

We're always happy to have a look over a PR!

Dom

**Comment by crhntr** [comment]
I believe this issue can be closed. Let me know if there is anything left to do.

**Comment by sergiolpf** [comment]
when is this being released?
