### ISSUE TITLE
Why is not bson:",inline" the default behaviour for embedded structs?

### ISSUE THREAD

**Issue by roobre** [globalsign/mgo#192]
I can definitely see as a good thing the `bson` package offering an option to force inlining of some fields, but I don't see why this isn't the default behavior for embedded structs. This is how other encoders (namely `encoding/json`) work.

Given the following scenario:

```go
type AStruct struct {
	Field   string
	BStruct
}

type BStruct struct {
	BField string
	Number int
}

var a AStruct
```

The json codec outputs `{"Field":"","BField":"","Number":0}`

While the bson codec outputs `8fieldbstructbfieldnumber%` (sorry for the garbage binary output, but you can clearly see there is a field named `bstruct` there.)

I'm not sure if this is intended or a bug. In any case, if you think this is worth changing, I can probably work on a PR.

Please let me know what you think.

**Comment by domodwyer** [comment]
Hi @roobre 

I'm not sure is the honest answer - we forked mgo and haven't changed anything that would break backwards compatibility to make the transition easier for users stuck after the original mgo was no longer maintained - this is one of them!

Sorry!
Dom

**Comment by roobre** [comment]
Hello,

I understand backwards-compatibility is a powerful reason here. Thanks for your response anyway.

Regards.
