### ISSUE TITLE
mongo查询数据集有点问题

### ISSUE THREAD

**Issue by xhochipe** [globalsign/mgo#194]
outs, err := bson.Marshal(m)
	   query := bson.M{}
	    for k, v := range m {
		  query = bson.M{k: v}
	   }
	  // var result []ReFeedback
	   var result1 []ReFeedback

	count, err := c.Find(outs).Count()
	conf.CheckErr(err)
	if size > 50 {
		size = 50
	}
	c.Find(outs).All(&result1)
         //c.Find(bson.M{"SecuCode": "000001"}).Skip(page * size).Limit(size).Sort("-timeDate").All(&result)

![image](https://user-images.githubusercontent.com/9391575/41584754-abd5a5d2-73da-11e8-8cb5-8734b349c45a.png)

你好：

同样都是用的outs这个结果，count可以查出来，但是下面的result1 查不出来，不是很理解，请教下博主

**Comment by domodwyer** [comment]
Hi @xhochipe 

Your `ReFeedback` struct must have the same names, or bson tags:

```go
type ReFeedback struct {
	Field1 string `bson:"field_name_1"`
	Field2 string `bson:"field_name_2"`
}
```

Where `field_name_1` is the name in mongo.

If this doesn't work, please post a runnable example - good luck!

Dom

**Comment by xhochipe** [comment]
@domodwyer

**Comment by xhochipe** [comment]
![Uploading QQ图片20180626175044.png…]()
![qq 20180626175037](https://user-images.githubusercontent.com/9391575/41903830-7c298ba2-7969-11e8-8047-54318b08fc80.png)

**Comment by domodwyer** [comment]
Hi @xhochipe 

It is very strange - do you have a test function I can run to reproduce? I tried something similar and it works OK for me.

Dom
