### ISSUE TITLE
Support changestreams

### ISSUE THREAD

**Issue by dalu** [globalsign/mgo#195]
[Changestreams](https://docs.mongodb.com/manual/changeStreams/) are a new feature of v3.6 and I'm not sure if they're supported by this driver.

If they're not I'd like to suggest adding support for them.

**Comment by dalu** [comment]
It's supported apparently
https://godoc.org/github.com/globalsign/mgo#Collection.Watch

**Comment by dalu** [comment]
Yeah I don't know. It doesn't work. Not with this driver, not with official driver, not even in mongo console.
Asked multiple times on IRC - no response.
That's why I wrote https://blog.icod.de/2018/07/22/go-database-changes-notifications-over-websocket-generic-solution-reactive-apps/

**Comment by yangkghjh** [comment]
I guess if return false means no change.Like this:

```go
	for {
		if ok := changeStream.Next(&changeDoc); ok {
			// there is a change, do some thing
		}
	}
```

If there is no change,  `changeStream.Next()` will return a false each second.
