### ISSUE TITLE
Connection Leak

### ISSUE THREAD

**Issue by pzillmann** [globalsign/mgo#209]
Git commit: current master
Go version: 1.9.4 linux/amd64

Connecting to a database inside a goroutine and exiting that goroutine doesn't free the connection.
The connection is held open even weeks after the goroutine is closed, quickly resulting in 820 connections and open files while only having 5 worker processes at any given time.

That means: mgo isn't checking whether the caller of `dial` is still running or the file-structure holding the session is not cleaned by the GC. mgo doesn't provide a function to call to `hangup` or end the connection.

Any suggestions are welcome.

**Comment by epelc** [comment]
@pzillmann do you have some example code for this? If you are copying the session in your goroutine you need to call `Close()`.

**Comment by pzillmann** [comment]
@epelc `defer session.Close()` would do the trick. But I'm creating a new session per Goroutine.
Is this wanted behavior.

```golang
package main

import (
	"log"
	"runtime"

	"github.com/globalsign/mgo"
)

type logdummy struct {
	test string
}

func (ld logdummy) Output(calldepth int, s string) error {
	log.Printf("Message: %s - LogLVL: %d", s, calldepth)
	return nil
}

func spawn() {
	_, err := mgo.Dial("user:pass@127.0.0.1/authDB")

	if err != nil {
		panic(err)
	}

	runtime.Goexit()
}

func main() {
	ld := logdummy{}

	mgo.SetLogger(ld)
	mgo.SetDebug(false)

	for i := 0; i < 10; i++ {
		go spawn()
	}

	block := make(chan bool)
	<-block
}
```

As you can see, the session is unreachable but still active / pinging every x seconds.

**Comment by epelc** [comment]
1. You should close he session when you are done with it ie at the end of your goroutine so use defer

2. Even better than the above. Dial once at startup and store a reference to it. In your goroutine call my session. Copy() and defer close on the copy. Then also defer close the main session in your main func so it’s closed on shutdown cleanly. 

2 is what you are supposed to really do. 1 is just basic usuage. You need to close sessions when you are done with them or else you are leaking them. This is the definition of leaking ie forgetting to do cleanup/closing.

**Comment by domodwyer** [comment]
Hi @pzillmann 

@epelc is right - thanks for helping out!

There's an example [here](https://godoc.org/github.com/globalsign/mgo#example-Session--Concurrency) that shows the best practise use of a session (including the `defer` as @epelc says!)

I'm going to close this as it's not an mgo issue.

Dom
