### ISSUE TITLE
Updating from older version that have written time.Duration causes bad data - maybe add a note?

### ISSUE THREAD

**Issue by flaterik** [globalsign/mgo#212]
We had been using an older version of the driver in production for some time, with many time.Duration values stored in the old nanos format. When we upgraded, all of those durations obviously came back 1e6 times larger than intended. Fixing the data was not difficult once we figured out what was wrong, and I do not foresee a code fix to this, but it might be nice to have a note about this change in the readme! It might save someone else the excitement that I had today.

**Comment by flaterik** [comment]
Sorry, I definitely could have provided more info! 
We moved from
package: gopkg.in/mgo.v2
version: 3f83fa5005286a7fe593b055f0d7771a7dce4655
(which I realize is quite old!)
to
package: github.com/globalsign/mgo
version: 113d3961e7311526535a1ef7042196563d442761
This is the change that affected things -
https://github.com/go-mgo/mgo/pull/373
And this is the code in question - 
https://github.com/globalsign/mgo/blob/113d3961e7311526535a1ef7042196563d442761/bson/encode.go#L439
In the older incarnations that case wasn't there, so the durations were stored as the underlying time.Duration int64. 
My solution was to scan our records and divide anything bigger than 1e15 by 1e6, which worked fine. Just had a period of time where things that were supposed to be five minutes were treated as if they should be 83,333.3333 hours.

**Comment by domodwyer** [comment]
Hi @flaterik 

I had forgotten about this! I think it was pulled into my fork before it became a globalsign fork, and once it started becoming popular we decided to not make breaking changes to help users transition - this slipped through!

Thanks for the issue, we'll update the docs!

Dom

**Comment by aitva** [comment]
Hi @domodwyer,

I am trying to migrate from `gopkg.in/mgo.v2` and I have the same issue. Is there a recommended way to fix this? Can you point me at the doc?

Thanks!
