### ISSUE TITLE
Remove `dropDups`

### ISSUE THREAD

**Issue by mhutter** [globalsign/mgo#214]
According to [the MongoDB docs](https://docs.mongodb.com/manual/reference/method/db.collection.createIndex/index.html#options-for-all-index-types), the `dropDups` option for indices has been removed in 3.0.

According to the Travis config the library is only tested against MongoDB 3.0 and greater. Do you want to keep deprecated features around for backwards-compatibility or should I open a PR to remove it? There may be more features that have been deprecated in 3.0...

**Comment by domodwyer** [comment]
Hi @mhutter 

I agree with you, happy to remove old things! I think we can safely assume <3.0 is unused at this point, it's been end-of-life'd by Mongo too. We'll happily accept a PR to remove the old bits 👍 

Dom
