### ISSUE TITLE
Add mongo 4.0 to travis CI

### ISSUE THREAD

**Issue by eminano** [globalsign/mgo#237]
Add last mongo version 4.0 to the continuous integration builds.

**Comment by peterdeka** [comment]
What is needed to close this? I saw just adding 4.0 as per PR #259 fails. Any clue? Something we can do?

**Comment by domodwyer** [comment]
Hi @peterdeka 

It looks like the error messages have changed, so the tests would need updating to match against them. There's probably other issues hiding away with 4.0 support though! I meant to close this when adding the [support note](https://github.com/globalsign/mgo#supported-versions) on the readme, but we are definitely interested in 4.0 support / PRs!

If there's anything I can do to help, please open tickets or reply here :)

Dom
