### ISSUE TITLE
How to get collection stats

### ISSUE THREAD

**Issue by angelocoiro** [globalsign/mgo#250]
I need to get collection stats like `db.mycollection.stats()`.
How can I do this with mgo?

**Comment by timvaillancourt** [comment]
Try the ["collStats"](https://docs.mongodb.com/manual/reference/command/collStats/) server command with the [.Run() func](https://godoc.org/github.com/globalsign/mgo#Session.Run).

**Comment by eminano** [comment]
Hi @angelocoiro,

Please try @timvaillancourt's suggestion. I'll close this issue, let me know if you have any further questions!

Esther
