### ISSUE TITLE
Panic invalid memory address or nil pointer

### ISSUE THREAD

**Issue by mzimmerman** [globalsign/mgo#260]
This is reproducible for me, however I'm working on finding a smaller sample.  Looking at the code, I'm not sure what's going wrong here as e is certainly non-nil as assigned way back in the stack.

Using commit as locked by dep tool - 4b08116de0de75c041bb341686f0b139930f26cb84dfdf7641d435548114181d

This results from a call to bulk.Run() of Insert() calls.

> panic: runtime error: invalid memory address or nil pointer dereference [recovered]
>         panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x45ba6f]
> 
> goroutine 1921465 [running]:
> vendor/github.com/globalsign/mgo/bson.handleErr(0xc9ccfc0e90)
>         /vendor/github.com/globalsign/mgo/bson/bson.go:525 +0x1ce
> panic(0xd5c940, 0x16d9b40)
>         /usr/lib/go/src/runtime/panic.go:502 +0x229
> vendor/github.com/globalsign/mgo/bson.(*encoder).addCStr(0xc9ccfc0e28, 0x0, 0x8)
>         /vendor/github.com/globalsign/mgo/bson/encode.go:611 +0x43
> vendor/github.com/globalsign/mgo/bson.(*encoder).addStr(0xc9ccfc0e28, 0x0, 0x8)
>         /vendor/github.com/globalsign/mgo/bson/encode.go:607 +0x5a
> vendor/github.com/globalsign/mgo/bson.(*encoder).addElem(0xc9ccfc0e28, 0xc940dae510, 0x5, 0xd0f1e0, 0xd2aa804388, 0x198, 0x100)
>         /vendor/github.com/globalsign/mgo/bson/encode.go:404 +0x1941
> vendor/github.com/globalsign/mgo/bson.(*encoder).addStruct(0xc9ccfc0e28, 0xfda7a0, 0xd2aa804360, 0x199)
>         /vendor/github.com/globalsign/mgo/bson/encode.go:254 +0x27a
> vendor/github.com/globalsign/mgo/bson.(*encoder).addDoc(0xc9ccfc0e28, 0xfda7a0, 0xd2aa804360, 0x199)
>         /vendor/github.com/globalsign/mgo/bson/encode.go:193 +0x2d8
> vendor/github.com/globalsign/mgo/bson.(*encoder).addElem(0xc9ccfc0e28, 0x109b24b, 0x1, 0xfda7a0, 0xd2aa804360, 0x199, 0x100)
>         /vendor/github.com/globalsign/mgo/bson/encode.go:573 +0xe4e
> vendor/github.com/globalsign/mgo/bson.(*encoder).addSlice(0xc9ccfc0e28, 0xd03a20, 0xca830b7510, 0x197)
>         /vendor/github.com/globalsign/mgo/bson/encode.go:341 +0x3d6
> vendor/github.com/globalsign/mgo/bson.(*encoder).addDoc(0xc9ccfc0e28, 0xd03a20, 0xca830b7510, 0x197)
>         /vendor/github.com/globalsign/mgo/bson/encode.go:195 +0x191
> vendor/github.com/globalsign/mgo/bson.(*encoder).addElem(0xc9ccfc0e28, 0xc940dae047, 0x7, 0xd03a20, 0xca830b7510, 0x197, 0x100)
>         /vendor/github.com/globalsign/mgo/bson/encode.go:480 +0x1d32
> vendor/github.com/globalsign/mgo/bson.(*encoder).addStruct(0xc9ccfc0e28, 0x1059260, 0xca830b7500, 0x199)
>         /vendor/github.com/globalsign/mgo/bson/encode.go:254 +0x27a
> vendor/github.com/globalsign/mgo/bson.(*encoder).addDoc(0xc9ccfc0e28, 0x1059260, 0xca830b7500, 0x199)
>         /vendor/github.com/globalsign/mgo/bson/encode.go:193 +0x2d8
> vendor/github.com/globalsign/mgo/bson.(*encoder).addElem(0xc9ccfc0e28, 0xccd71f03fc, 0x3, 0x1059260, 0xca830b7500, 0x199, 0x0)
>         /vendor/github.com/globalsign/mgo/bson/encode.go:573 +0xe4e
> vendor/github.com/globalsign/mgo/bson.(*encoder).addElem(0xc9ccfc0e28, 0xccd71f03fc, 0x3, 0x10165c0, 0xca830b7500, 0x16, 0x0)
>         /vendor/github.com/globalsign/mgo/bson/encode.go:376 +0xc30
> vendor/github.com/globalsign/mgo/bson.(*encoder).addElem(0xc9ccfc0e28, 0xccd71f03fc, 0x3, 0xd348c0, 0xceea36b720, 0x194, 0x100)
>         /vendor/github.com/globalsign/mgo/bson/encode.go:373 +0xcfc
> vendor/github.com/globalsign/mgo/bson.(*encoder).addSlice(0xc9ccfc0e28, 0xd03260, 0xd0d3d6ae80, 0x97)
>         /vendor/github.com/globalsign/mgo/bson/encode.go:341 +0x3d6
> vendor/github.com/globalsign/mgo/bson.(*encoder).addDoc(0xc9ccfc0e28, 0xd03260, 0xd0d3d6ae80, 0x97)
>         /vendor/github.com/globalsign/mgo/bson/encode.go:195 +0x191
> vendor/github.com/globalsign/mgo/bson.(*encoder).addElem(0xce00510e28, 0x106eab6, 0x9, 0xd03260, 0xd0d3d6ae80, 0x97, 0xe72400)
>         /vendor/github.com/globalsign/mgo/bson/encode.go:480 +0x1d32
> vendor/github.com/globalsign/mgo/bson.(*encoder).addSlice(0xc9ccfc0e28, 0xd46d40, 0xd0d3d6aea0, 0x97)
>   /vendor/github.com/globalsign/mgo/bson/encode.go:314 +0x12d
> vendor/github.com/globalsign/mgo/bson.(*encoder).addDoc(0xc9ccfc0e28, 0xd46d40, 0xd0d3d6aea0, 0x97)
>         /vendor/github.com/globalsign/mgo/bson/encode.go:195 +0x191
> vendor/github.com/globalsign/mgo/bson.MarshalBuffer(0xd46d40, 0xd0d3d6aea0, 0xd42220c000, 0x27, 0x58c000, 0x0, 0x0, 0x0, 0x0, 0x0)
>         /vendor/github.com/globalsign/mgo/bson/bson.go:584 +0xd4
> vendor/github.com/globalsign/mgo.addBSON(0xd42220c000, 0x27, 0x58c000, 0xd46d40, 0xd0d3d6aea0, 0x20, 0x1065880, 0x106bcd0, 0x7, 0x0)
>         /vendor/github.com/globalsign/mgo/socket.go:726 +0xf7
> vendor/github.com/globalsign/mgo.(*mongoSocket).Query(0xd026fa0a20, 0xc9ccfc14b8, 0x1, 0x1, 0x0, 0x0)
>         /vendor/github.com/globalsign/mgo/socket.go:485 +0x1099
> vendor/github.com/globalsign/mgo.(*mongoSocket).SimpleQuery(0xd026fa0a20, 0xcb74859860, 0x5, 0x1068f81, 0x5, 0xd42b2a8a40, 0xa)
>         /vendor/github.com/globalsign/mgo/socket.go:404 +0x1a2
> vendor/github.com/globalsign/mgo.(*Database).run(0xd0d3d6ae40, 0xd026fa0a20, 0xd46d40, 0xd0d3d6aea0, 0xd3cac0, 0xcbfd3e06c0, 0xd0cc92a930, 0x70f467)
>         /vendor/github.com/globalsign/mgo/session.go:3878 +0x1c2
> vendor/github.com/globalsign/mgo.(*Collection).writeOpCommand(0xcb7799d6b0, 0xd026fa0a20, 0xc420df00f0, 0xc8a720, 0xcb7799d6e0, 0x410000, 0x1a0, 0x102c420, 0xd0e501)
>         /vendor/github.com/globalsign/mgo/session.go:5547 +0x211
> vendor/github.com/globalsign/mgo.(*Collection).writeOp(0xcb7799d6b0, 0xc8a720, 0xcb7799d6e0, 0x0, 0x0, 0x0, 0x0)
>         /vendor/github.com/globalsign/mgo/session.go:5406 +0x53b
> vendor/github.com/globalsign/mgo.(*Bulk).runInsert(0xc9ccfc1e60, 0xd1d3ebba40, 0xc6036eaca0, 0xd0d3d6ae60, 0xceea36bff0)
>         /vendor/github.com/globalsign/mgo/bulk.go:325 +0xbe
> vendor/github.com/globalsign/mgo.(*Bulk).Run(0xc9ccfc1e60, 0xd0cc92ae18, 0x1, 0x1)
>         /vendor/github.com/globalsign/mgo/bulk.go:295 +0x28b

**Comment by mzimmerman** [comment]
- go version  go1.10.3 linux/amd64
- mongodb version v4.0.0
- arch linux (4.18.5-arch1-1-ARCH SMP PREEMPT Fri Aug 24 12:48:58 UTC 2018 x86_64 GNU/Linux)
- mgo version  6f9f54a

I'll work on the reproducible build, but to be honest, for now (cause I need to keep going), I just put the call to Run() in a func() with defer() and recover()....

**Comment by domodwyer** [comment]
Hi @mzimmerman 

We don't provide any guarantees for Mongo 4.0 at the moment, it's a significant change and `mgo` has not had the time to evolve to support it - sorry!

I'll update the README with a list of supported versions - if you track down the underlying issue however we _are_ very interested in PRs for 4.0 support, it's just going to take a little time to get `mgo` to support 4.0 - every PR helps! :)

Dom
