### ISSUE TITLE
What did mgo do with file descriptor 4?

### ISSUE THREAD

**Issue by jinliming2** [globalsign/mgo#262]
First of all, I wrote this code:
```go
package main

import (
	"net"
	"os"
)

func main() {
	// I need to inherit file descriptors from the parent process.
	file := os.NewFile(uintptr(4), "")
	err := file.Close()
	if err != nil {
		println("A", err.Error())
	}

	_, err = net.ListenTCP("tcp", &net.TCPAddr{Port: 80})
	if err != nil {
		println("B", err.Error())
	}
}
```
This works fine, Error A should be output in anticipation, and Error B should not.
Then, I imported the mgo:
```go
package main

import (
	"net"
	"os"

	"github.com/globalsign/mgo"
)

func main() {
	// I need to inherit file descriptors from the parent process.
	file := os.NewFile(uintptr(4), "")
	err := file.Close()
	if err != nil {
		println("A", err.Error())
	}

	_, err = net.ListenTCP("tcp", &net.TCPAddr{Port: 80})
	if err != nil {
		println("B", err.Error())
	}

	println(mgo.Default) // Just for keep mgo imported.
}
```
Now, Error A not outputted, and I got Error B outputted: `B listen tcp :80: bad file descriptor`.

Actually, I need to inherit the file descriptor 3, 4 and 5 from the parent process.
If I only inherit the **file descriptor 3**, it works fine, and neither Error A nor Error B outputted.
If I only inherit the **file descriptor 5**, it works fine, and just like I wasn't imported the mgo, only Error A outputted.
Or, if I didn't import the mgo, everything works fine.
Only if I imported the mgo and inherit the **file descriptor 4** in the same time, the Error B outputted and I can't listen on TCP port 80.

What should I do? Was I did something wrong?

**Comment by domodwyer** [comment]
Hi @jinliming2 

How are you creating the child process? A `fork` syscall followed by an `execvp` or something similar?

Dom

**Comment by jinliming2** [comment]
@maitesin I'm running this with Go 1.10.3 in macOS High Sierra, too.

The reason you can't reproduce the behaviour of the first code is you need to run this code with sudo to listen on the port less than 1024.

```go
sudo go run example1.go
```

**Comment by jinliming2** [comment]
@domodwyer I'm trying to open file descriptor 3, 4 and 5 and create TCP File Listener on each of them.
The parent process creates the child process with `syscall.ForkExec`. But now I'm running this directly.

**Comment by domodwyer** [comment]
Hi @jinliming2 

File descriptors are per-process, you need to run via `ForkExec` to "inherit" the correct fd, you can't just do `go run`.

This isn't really an mgo issue - mgo may open fds in the background, but so may any package you import. It's kinda out of scope for a database driver.

I'd suggest looking into passing the fd directly (either via a unix socket, some other IPC, or maybe even exec args) rather than hard-coding the fd number - it will be far more robust.

Hope this helps!

Dom
