### ISSUE TITLE
poll.runtime_pollWait

### ISSUE THREAD

**Issue by ByLuxury** [globalsign/mgo#268]
goroutine 337 [IO wait]:
internal/poll.runtime_pollWait(0x7f1a467aa0e0, 0x72, 0xc420665d18)
	/usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc4201fc798, 0x72, 0xffffffffffffff00, 0xbf5120, 0x1190590)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0x9b
internal/poll.(*pollDesc).waitRead(0xc4201fc798, 0xc420272900, 0x24, 0x24)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc4201fc780, 0xc420272960, 0x24, 0x24, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:157 +0x17d
net.(*netFD).Read(0xc4201fc780, 0xc420272960, 0x24, 0x24, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc4203950e8, 0xc420272960, 0x24, 0x24, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:176 +0x6a
gitlab.com/asset-exchange/asset-curd/vendor/github.com/globalsign/mgo.fill(0xbfd1c0, 0xc4203950e8, 0xc420272960, 0x24, 0x24, 0x0, 0x18)
	/go/src/gitlab.com/asset-exchange/asset-curd/vendor/github.com/globalsign/mgo/socket.go:584 +0x53
gitlab.com/asset-exchange/asset-curd/vendor/github.com/globalsign/mgo.(*mongoSocket).readLoop(0xc4201f3d40)
	/go/src/gitlab.com/asset-exchange/asset-curd/vendor/github.com/globalsign/mgo/socket.go:600 +0x602
created by gitlab.com/asset-exchange/asset-curd/vendor/github.com/globalsign/mgo.newSocket
	/go/src/gitlab.com/asset-exchange/asset-curd/vendor/github.com/globalsign/mgo/socket.go:200 +0x20b

**Comment by domodwyer** [comment]
Hi @ByLuxury 

Please provide some sort of information - this stack trace is normal.

**Comment by Kathent** [comment]
hello, I run into the same situation,  after a benchmark just create and find op over, I found about 68 goroutines stuck,  and I check the function 'socket.readLoop',  it didn't set the timeout for the first time

**Comment by Kathent** [comment]
Hi @domodwyer,  I confirmed my thought by moving the method updateDeadline ahead to the start of the loop,  and then the no stuck goroutines.   I wonder whether this is a bug or some normal logic just what it is.  please give me some replies. thx
