### ISSUE TITLE
Mongodb 3.4.x support

### ISSUE THREAD

**Issue by feliixx** [globalsign/mgo#27]
Currently some features of MongoDB 3.4.x are implemented ( **collations** for example) but aren't documented ( [Query.Collation()](https://godoc.org/github.com/globalsign/mgo#Query.Collation), views...), and some other aren't implemented at all (see [#484](https://github.com/go-mgo/mgo/issues/484) ) 

In addition, test aren't run against mongo 3.4.x in Travis CI, so it's not very clear whether this serie is supported or not. 

So is there any plans to fully support Mongodb 3.4? 

If nobody is working on this, I'm interested in doing it !

**Comment by domodwyer** [comment]
Hi @feliixx 

So 3.4 is supported (but as you said, partially) - I'm very interested in the `appName` parameter (https://github.com/go-mgo/mgo/issues/484) and was planning on implementing it myself when I had the time - if you'd like to, please do! I'll help however I can :)

Obviously views are a good nice-to-have and may become more of a priority for us in the future, I haven't looked into how much work they'd take to implement though.

The tests are somewhat tricker - I had a quick go at getting them running against 3.4 when we originally forked mgo, but the whole test harness thing is less than perfect... Again, if you want to/can, I'll help however I can!

Thanks,
Dom

**Comment by domodwyer** [comment]
As a side note, we'll happily host the 3.4 binaries for the travis tests if you decide to have a crack at it - just let us know and we'll get them uploaded.

Dom

**Comment by feliixx** [comment]
@domodwyer Thanks, that would be great ! I started working on `appName` parameter, see PR #28

**Comment by domodwyer** [comment]
Hey @feliixx, thanks for the PR!

I've split this issue into individual feature request issues so we can close them as we go along:

- Collation https://github.com/globalsign/mgo/issues/29
- Views https://github.com/globalsign/mgo/issues/30
- Integration tests https://github.com/globalsign/mgo/issues/31

I'm going to close this ticket and switch to the above :) Thanks for bringing it up.

Dom
