### ISSUE TITLE
Support automatic retries on "duplicate key errors" in upsert queries

### ISSUE THREAD

**Issue by xapon** [globalsign/mgo#274]
When running `upsert` queries, its is possible that multiple clients will try to create records with the same primary key, resulting in a duplicate key error (E11000).
This is a documented (https://jira.mongodb.org/browse/SERVER-14322), while somewhat counterintuitive, behavior of the database, with a recommendation for a client to retry the query. That's what I'm currently doing in my application.

However, I believe a convenient workaround could be added to the driver to retry such failing upsert queries.
This can be done as an additional method such as `collection.UpsertWithRetry` and `collection.Bulk().UpsertWithRetry()` to keep this backwards-compatible, and make sure clients choose this behavior deliberately.

If you think this will be a usefull addition to the library, I would be happy to try implementing it myself.

**Comment by eminano** [comment]
Hi @xapon,

To do what you're suggesting would mean having to detect and decide under which conditions the upsert should retry on the driver. A collection could have multiple unique constraints and it's possible not all cases would fit the case of a retry. 

I believe this is the kind of logic that should be kept on the client side, giving the flexibility to decide how to behave in such an edge case. 

Thanks a lot for your suggestion and for your disposition to help though!

Esther
