### ISSUE TITLE
Go modules support

### ISSUE THREAD

**Issue by jerome-laforge** [globalsign/mgo#283]
Hello
Could you tag with support [semantic version](https://semver.org/)?
Could you add go.mod in order to define all dependencies?

Thx
Jérôme

**Comment by maitesin** [comment]
Hi @jerome-laforge ,

Thanks for taking the time to write this issue. Regarding the tag version, it was changed not long ago to work better with [dep](https://golang.github.io/dep/), please see issue #193. What the reason why you are requesting the usage of a semantic version?

We are happy to review pull requests, so feel free to send one with the change to add the `go.mod` file with the dependencies.

Best regards,
Oscar

**Comment by jerome-laforge** [comment]
Hi @maitesin,
> Thanks for taking the time to write this issue. Regarding the tag version, it was changed not long ago to work better with dep, please see issue #193. What the reason why you are requesting the usage of a semantic version?

From my point of view, the semantic version is good way to manage dependency (c.f. https://github.com/golang/go/wiki/Modules#semantic-import-versioning). By the way, go modules, that will be official way to manage dependencies, requires semantic version for `Version Selection`(c.f. https://github.com/golang/go/wiki/Modules#version-selection)

>We are happy to review pull requests, so feel free to send one with the change to add the go.mod file with the dependencies.

Ok, I will try to do that ;)

Thx for your support
Best regards,
Jérôme

**Comment by vladbarosan** [comment]
@maitesin Agree with @jerome-laforge I think everyone agrees that Semantic Version is the way to go. Also in the issue #193 you mentioned it was promised that future versions will work with dep but as of now, no new release has been made, will you make any new releases soon?  Also will that release conform with semantic versioning ( e.g. v2018.11.20 wont have any breaking changes introduced in v2018.10.10) ? 
Also not having semantic is a big blocker for us, especially moving forward towards modules.

**Comment by dsvensson** [comment]
Any chance this could be released, tagged etc, any time soon? go-openapi depends on this, and one project I'm working on depends of go-openapi, and it seems like the lack of a go.mod breaks the bingo go language server.

**Comment by pierrre** [comment]
It seems https://github.com/go-openapi/strfmt requires `mgo` for the `bson` package only.

Maybe open an issue on https://github.com/go-openapi/strfmt and ask them to migrate to the official Go driver ?
The v1.0.0 has been released recently.
https://github.com/mongodb/mongo-go-driver

**Comment by domodwyer** [comment]
Yeah, it's probably best to move to the official driver - mgo is old code and doesn't have the development support that MongoDB is providing for their official driver!

On a related note, go.mod was merged into development several months ago so I will close this ticket.

Dom
