### ISSUE TITLE
Run integration tests against MongoDB 3.4.X

### ISSUE THREAD

**Issue by domodwyer** [globalsign/mgo#31]
Currently we run integration tests against the `2.6.X`, `3.0.X` and `3.2.X` releases of MongoDB.

We should also run against `3.4.X` - this is tricky as the test harness is difficult to work with.

If anyone wants to take a crack at it we're happy to host the binaries as we do for the other versions, see [travis.yml](https://github.com/globalsign/mgo/blob/master/.travis.yml) - just leave a message below and we'll get the latest version uploaded.

**Comment by feliixx** [comment]
I'll try to make the test pass against 3.4.x, please let me know when the binaries are uploaded !

**Comment by domodwyer** [comment]
Hey @feliixx 

The integration tests on 3.4.X are a bit of a priority if we're adding more 3.4.X features (mostly by you!), thanks very much. The test harness is a bit tricky to work with, I was going to look at replacing it with [mlaunch](https://github.com/rueckstiess/mtools/wiki/mlaunch) from the mtools script collection to try and make it easier to work with - I dunno if this will work (it might even be harder to replace the whole lot) but might be worth checking - up to you.

If you run into any trouble let me know and I'll help where I can, again, **thanks**!

The binary is [here](https://s3.eu-west-2.amazonaws.com/globalsign-mgo/mongodb-linux-x86_64-3.4.8.tgz), you can add:

```
- GO=1.8.x MONGODB=x86_64-3.4.8
```
to the `env.matrix` array in `.travis.yml` to get it to run (you might want to remove the others for testing - they take a while).

Best of luck!
Dom
