### ISSUE TITLE
$near/$geoNear doesn't work for me

### ISSUE THREAD

**Issue by Emixam23** [globalsign/mgo#332]
Hey !

I am coming because I need to realize geocalculs, however, it doesn't work..

From the doc we have this:

    db.<collection>.find( { <location field> :
            { $near :
                { $geometry :
                    { type : "Point" ,
                         coordinates : [ <longitude> , <latitude> ] } ,
                         $maxDistance : <distance in meters>,
                    } 
                }
           }
      )

Query a *2dsphere* index : https://docs.mongodb.com/manual/tutorial/query-a-2dsphere-index/
*2dsphere* Indexes : https://docs.mongodb.com/manual/core/2dsphere/

So I have the following:

    import (
		"github.com/globalsign/mgo/bson"
		"shared/models"
		"time"
	)
	
	type Address struct {
		ID                 *bson.ObjectId `protobuf:"bytes,1,opt,name=id,proto3" json:"_id,omitempty" bson:"_id"`
		IsArchived         bool           `protobuf:"varint,2,opt,name=IsArchived,proto3" json:"is_archived,omitempty" bson:"is_archived"`
		CreatedAt          time.Time      `protobuf:"varint,3,opt,name=CreatedAt,proto3" json:"created_at,omitempty" bson:"created_at"`
		UpdatedAt          time.Time      `protobuf:"varint,4,opt,name=UpdatedAt,proto3" json:"update_at,omitempty" bson:"updated_at"`
		PlaceID            *bson.ObjectId `protobuf:"bytes,5,opt,name=PlaceID,proto3" json:"place_id,omitempty" bson:"place_id"`
		CountryCode        string         `protobuf:"bytes,6,opt,name=CountryCode,proto3" json:"country_code,omitempty" bson:"country_code,omitempty"`
		AdministrativeArea string         `protobuf:"bytes,7,opt,name=AdministrativeArea,proto3" json:"administrative_area,omitempty" bson:"administrative_area,omitempty"`
		Locality           string         `protobuf:"bytes,8,opt,name=Locality,proto3" json:"locality,omitempty" bson:"locality,omitempty"`
		PostalCode         string         `protobuf:"bytes,9,opt,name=PostalCode,proto3" json:"postal_code,omitempty" bson:"postal_code,omitempty"`
		Thoroughfare       string         `protobuf:"bytes,10,opt,name=Thoroughfare,proto3" json:"thoroughfare,omitempty" bson:"thoroughfare,omitempty"`
		Premise            string         `protobuf:"bytes,11,opt,name=Premise,proto3" json:"premise,omitempty" bson:"premise,omitempty"`
		Location           GeoJson `protobuf:"bytes,12,opt,name=Location,proto3" json:"location,omitempty" bson:"location,omitempty"`
	}

    type GeoJson struct {
		Type        string    `json:"-"`
		Coordinates []float64 `json:"coordinates"`
	}

    var addresses []*models.Address
    collection := _session.DB(constants.DBName).C(documentName)
    err := collection.Find(session, addressDocument, bson.M{
		"location": bson.M{
			"$near": bson.M{
				"$geometry": bson.M{
					"type":        "Point",
					"coordinates": []float64{ -115.172813, 36.101379 },
				},
				"$maxDistance": 5000000,
			},
		},
	}) &addresses)

From this, I got the following error:

> "error processing query: ns=DBNAME.addressDocumentTree: GEONEAR  field=location maxdist=5e+06 isNearSphere=0\nSort: {}\nProj: {}\n planner returned error: unable to find index for $geoNear query"

**I ensure my index at the initialization of my program**

    // EnsureIndex
    func EnsureAddressIndex(session *mgo.Session) error {

	_session := session.Copy()
	defer _session.Close()

	c := _session.DB(constants.DBName).C(addressDocument)
	// Might be needed one day
	pIndex := mgo.Index{
		Key:  []string{"location:2dsphere"},
		Bits: 26,
	}
	err := c.EnsureIndex(pIndex)
	if err != nil {
		return err
	}

	return nil
    }

Any idea? I have more than 20k addresses and they all have lat/lng ... :(

Thanks !

**Comment by domodwyer** [comment]
Hi @Emixam23 

There's an experimental (read: unsupported) API for geospatial queries in the [geospatial-geoNear](https://github.com/globalsign/mgo/tree/feature/geospatial-geoNear) branch - check [these commits](https://github.com/globalsign/mgo/commits/feature/geospatial-geoNear) - maybe they can help you!

Dom

**Comment by Emixam23** [comment]
Hey ! 

Finally found the issue.. Actually, I wasn't creating the index in the right way..

    // EnsureIndex force ids to be unique
	func EnsureAddressIndex(session *mgo.Session) error {
	
		_session := session.Copy()
		defer _session.Close()
	
		c := _session.DB(constants.DBName).C(addressDocument)
		// Might be needed one day
		pIndex := mgo.Index{
			Key:  []string{"$2dsphere:location"},
			Bits: 26,
		}
		err := c.EnsureIndex(pIndex)
		if err != nil {
			return err
		}
	
		return nil
	}

At the index declaration, I had the following line:

    pIndex := mgo.Index{
        Key:  []string{"location:2dsphere"},
        Bits: 26,
    }

But the correct way to write it is

    pIndex := mgo.Index{
        Key:  []string{"$2dsphere:location"},
        Bits: 26,
    }

Hope it helps !

**Comment by domodwyer** [comment]
Awesome! Thanks for reporting back 👍 

Dom

**Comment by Emixam23** [comment]
Of course, you're welcome :) It perfectly works as far as I could see.

Max
