### ISSUE TITLE
Setting the maxPoolSize has no effect

### ISSUE THREAD

**Issue by tokingHong** [globalsign/mgo#336]
before test
![image](https://user-images.githubusercontent.com/39825820/54685145-0633c100-4b51-11e9-9690-ad00928c1bee.png)
![image](https://user-images.githubusercontent.com/39825820/54685151-0b910b80-4b51-11e9-84a2-e7ba80638898.png)
no connections

```go
func TestUserRepository_GetUserList(t *testing.T) {
	session ,_ =  mgo.Dial("mongodb://10.124.203.14:27017/user?maxPoolSize=10")
	session.SetPoolLimit(10)
	for i:=0;i<300;i++ {
		//time.Sleep(time.Millisecond*2)
		  go func() {
		  	var xx []interface{}
		  	copySession := session.Clone()
		  	copySession.DB("user").C("user").Find(nil).All(&xx)
		  	copySession.Close()
		  	utils.Debugf("xxx")
		  }()
	}
	//time.Sleep(10*time.Second)
	select {

	}
}
```

![image](https://user-images.githubusercontent.com/39825820/54685183-26fc1680-4b51-11e9-96cf-9632ac921628.png)
![image](https://user-images.githubusercontent.com/39825820/54685190-295e7080-4b51-11e9-903a-559ecdb55003.png)

Why the maxPoolSize had no effect?

go version 1.10
mgo is latest

**Comment by domodwyer** [comment]
Hi @tokingHong 

Cloning a session is [documented](https://godoc.org/github.com/globalsign/mgo#Session.Clone) to reuse the same socket:

> Clone works just like Copy, but also reuses the same socket as the original session

I guess your connections are coming from somewhere else?

I'm going to close this, feel free to reply if you think it is definitely a mgo issue though!
Dom

**Comment by tokingHong** [comment]
@domodwyer You can check my code and have a test :)
