### ISSUE TITLE
Should the time use Local instead of UTC ?

### ISSUE THREAD

**Issue by wzshiming** [globalsign/mgo#341]
https://github.com/globalsign/mgo/blob/eeefdecb41b842af6dc652aaea4026e8403e62df/bson/decode.go#L724

**Comment by eminano** [comment]
Hi @wzshiming,

It's standard practice (and a good idea) to use UTC instead of local, since it guarantees consistent timestamps. If you have the need for local time, you should handle the conversion on your end.

Cheers,
Esther
