### ISSUE TITLE
Gratuitous time zone remapping breaks user code

### ISSUE THREAD

**Issue by derrickburns** [globalsign/mgo#345]
https://github.com/globalsign/mgo/pull/42

breaks all user code that compares original versus retrieved versions of a Mongo object with an embedded time field Time objects if the original version is not in UTC.

This includes  practically all Gomega Unit tests that use DeepEqual on structs with Time objects.

This was a bad idea.

**Comment by domodwyer** [comment]
Hi @derrickburns 

Thanks for the ticket - perhaps you're looking for https://golang.org/pkg/time/#Time.Equal

Best wishes.
