### ISSUE TITLE
Considering switching to globalsign/mgo

### ISSUE THREAD

**Issue by qhenkart** [globalsign/mgo#59]
Hey guys, my co-workers and I are impressed by how well you're maintaining this project, and we are considering switching from the neglected go-mgo driver to your repo. 

We have two quick questions if you don't mind:

1) We are wondering if you guys are keeping your repo up to date with new commits from 10gen/mgo, or do you work completely independently of them?

2) Do you know if there are any plans to classify this repo or the 10gen one as the "official" driver?

Thank you for taking them time to maintain this repo. We were relieved to find such an active and well maintained driver solution.

**Comment by domodwyer** [comment]
Hi @qhenkart 

First off thanks for your kind words!

We keep an eye on both the 10gen repo, and the original go-mgo repo, pulling anything of use over into this - that's actually how this started, I was just keeping a "best of" repo for our own use. Now it's grown into mostly organic changes from the many [fantastic contributors](https://github.com/globalsign/mgo/blob/development/README.md#thanks-to) (thanks!) - if there's anything not pulled across that you think should be included just open a PR.

Regarding your second point I've had no communication with Mongo, however it was pointed out that this fork was listed on their [community driver page](https://docs.mongodb.com/ecosystem/drivers/community-supported-drivers/) recently. The original fork seems to have [chosen not to become "official"](https://github.com/go-mgo/mgo/issues/416#issuecomment-290464557) for whatever reason.

I don't think either fork is likely to be "official" in the near future, the 10gen repo seems mostly geared to testing mongo features (I'm guessing from their commits here).

The health of this fork is as much down to the many contributors as it is ourselves so we can't take all the credit :) Thanks though!

Dom
