### ISSUE TITLE
Missing insertedId field in return when inserting new document

### ISSUE THREAD

**Issue by narinder-kaur** [globalsign/mgo#62]
Hi,
I am using version 3.4 of mongodb and its supporting db.collection.insertOne(), db.collection.inserMany()
As per requirement, I need to have the last insert id from the db. Mongodb is returning it but func (c *Collection) Insert(docs ...interface{}) error method is returning the error only, though I supposed to have the insertedId as well.

**Comment by domodwyer** [comment]
Hi @narinder-kaur 

You're right, currently the driver does not support this - we would be more than happy to accept a PR for it!

Dom
