### ISSUE TITLE
Noob setup

### ISSUE THREAD

**Issue by bimalkharel** [globalsign/mgo#64]
Hi,

I have been tasked with setting up and testing go against mongodb (I am a dba). I need to prepare the basics for a developer to get productive. Are there docs on how to build this or use it in a simple CRUD app written in go?

Thanks!

**Comment by domodwyer** [comment]
Hi @bimalkharel!

We don't have any examples as part of this repo (yet, it's a good idea!) but there's always the [documentation](https://godoc.org/github.com/globalsign/mgo) - if you need actual code to have a look at there's some simple CRUD functions implemented [here](https://github.com/domodwyer/mpjbt/blob/master/mongo/db_opts.go). Connecting is easier than what's shown in that file as it provides more options to the caller but the basics are there.

The general idea is to [Dial()](https://godoc.org/github.com/globalsign/mgo#Dial) a connection and then [Copy()](https://godoc.org/github.com/globalsign/mgo#Session.Copy) a child session for each concurrent worker to use (make sure to [Close()](https://godoc.org/github.com/globalsign/mgo#Session.Copy) the returned session - this returns it to the internal connection pool).

Good luck!
Dom

**Comment by bimalkharel** [comment]
Thanks!
