### ISSUE TITLE
Question: is Find(...).Limit(1).One(...) equivalent to Find(...).One(...)

### ISSUE THREAD

**Issue by JordanP** [globalsign/mgo#66]
Hi,
I tried to answer that question myself but I can't figure out the code exactly. Do you happen to know the answer ?

Thanks !

**Comment by domodwyer** [comment]
Hi @JordanP 

Yes it is the same - check https://github.com/globalsign/mgo/blob/master/session.go#L3391

Calling `One()` runs a `findCmd` with a limit of 1 the same as if you called `Limit(1)`:
```go
expectFindReply := prepareFindOp(socket, &op, 1)
```

```go
func prepareFindOp(socket *mongoSocket, op *queryOp, limit int32) bool {
	// <snip>

	find := findCmd{
		// <snip>

		Limit: limit,
	}
	
	// <snip>
}
```

**Comment by JordanP** [comment]
Thank you !
