### ISSUE TITLE
New 3.6 features support

### ISSUE THREAD

**Issue by IAD** [globalsign/mgo#70]
we have new features like `change streams` and `lookup` in 3.6 https://docs.mongodb.com/manual/release-notes/3.6/
anybody plan to implement support?

**Comment by IAD** [comment]
ok. see https://github.com/globalsign/mgo/pull/38

**Comment by domodwyer** [comment]
Hi @IAD,

Yes we plan on adding 3.6 features as we go along, though it will be quicker with the help of others - see https://github.com/globalsign/mgo/pull/61 and https://github.com/globalsign/mgo/pull/68 by @feliixx and the ongoing #38 as you say.

We don't currently have any plans for `lookup` - we're always happy to get a good PR though!

Dom
