### ISSUE TITLE
Watch a Change Stream

### ISSUE THREAD

**Issue by phacops** [globalsign/mgo#83]
I believe there's no way right now to watch a change stream with mgo. It would be great if this feature could be added.

I noticed a branch with some work started on this. I'm bringing it up-to-date with master and will start testing with that.

https://docs.mongodb.com/manual/changeStreams

**Comment by domodwyer** [comment]
Hi @phacops, 

You're right, the work-in-progresss https://github.com/globalsign/mgo/pull/38 is the only changeStream support currently - it would be fantastic if you could bring it up to speed!

Let me know if there's anything I can do to help you.

Dom

**Comment by domodwyer** [comment]
Hi @phacops 

I'm going to close this issue but please do feel free to open a PR!

Dom
