### ISSUE TITLE
how to get tests to pass?

### ISSUE THREAD

**Issue by rogpeppe** [globalsign/mgo#84]
If I run the tests (after successfully running make startdb), I consistently get cluster_test failures.

Is there anything I can do to make tests pass?
(running this against MongoDB 3.6.2)

	----------------------------------------------------------------------
	FAIL: cluster_test.go:527: S.TestModeMonotonicFallover
	
	cluster_test.go:556:
	    c.Assert(err, Equals, io.EOF)
	... obtained = nil
	... expected *errors.errorString = &errors.errorString{s:"EOF"} ("EOF")
	
	----------------------------------------------------------------------
	FAIL: cluster_test.go:570: S.TestModeMonotonicWithSlaveFallover
	
	Running serverStatus and isMaster with monotonic session
	cluster_test.go:646:
	    // ... which is not the old one, since it's still dead.
	    c.Assert(ssresult.Host, Not(Equals), master)
	... obtained string = "snazzy:40021"
	... expected string = "snazzy:40021"
	
	----------------------------------------------------------------------
	
	FAIL: cluster_test.go:819: S.TestModePrimaryFallover
	
	cluster_test.go:843:
	    c.Assert(err, ErrorMatches, "no reachable servers")
	... value = nil
	... regex string = "no reachable servers"
	... Error value is nil
	
	----------------------------------------------------------------------
	FAIL: cluster_test.go:476: S.TestModePrimaryHiccup
	
	cluster_test.go:510:
	    c.Assert(err, Equals, io.EOF)
	... obtained = nil
	... expected *errors.errorString = &errors.errorString{s:"EOF"} ("EOF")
	
	----------------------------------------------------------------------
	FAIL: cluster_test.go:776: S.TestModePrimaryPreferredFallover
	
	cluster_test.go:797:
	    c.Assert(err, Equals, io.EOF)
	... obtained = nil
	... expected *errors.errorString = &errors.errorString{s:"EOF"} ("EOF")
	
	----------------------------------------------------------------------
	
	FAIL: cluster_test.go:717: S.TestModeSecondaryPreferredFallover
	
	Waiting for cluster sync to finish...
	
	cluster_test.go:759:
	    c.Assert(err, Equals, io.EOF)
	... obtained = nil
	... expected *errors.errorString = &errors.errorString{s:"EOF"} ("EOF")
	
	----------------------------------------------------------------------
	
	FAIL: cluster_test.go:435: S.TestModeStrongFallover
	
	cluster_test.go:455:
	    c.Assert(err, Equals, io.EOF)
	... obtained = nil
	... expected *errors.errorString = &errors.errorString{s:"EOF"} ("EOF")
	
	----------------------------------------------------------------------
	FAIL: cluster_test.go:1819: S.TestNearestSecondary
	
	cluster_test.go:1878:
	    c.Assert(hostPort(result.Host), Equals, hostPort(rs1b))
	... obtained string = "40013"
	... expected string = "40012"
	
	----------------------------------------------------------------------
	
	FAIL: cluster_test.go:1764: S.TestPrimaryShutdownOnAuthShard
	
	cluster_test.go:1796:
	    c.Assert(err, Equals, io.EOF)
	... obtained = nil
	... expected *errors.errorString = &errors.errorString{s:"EOF"} ("EOF")
	
	----------------------------------------------------------------------
	
	FAIL: cluster_test.go:1491: S.TestRemovalOfClusterMember
	
	cluster_test.go:1556:
	    c.Assert(err, NotNil)
	... value = nil
	
	----------------------------------------------------------------------
	
	FAIL: cluster_test.go:1470: S.TestSecondaryModeWithMongosInsert
	
	cluster_test.go:1488:
	    c.Assert(result.A, Equals, 1)
	... obtained int = 0
	... expected int = 1
	
	----------------------------------------------------------------------
	
	FAIL: cluster_test.go:986: S.TestSyncTimeout
	
	cluster_test.go:1004:
	    c.Assert(err, ErrorMatches, "no reachable servers")
	... value = nil
	... regex string = "no reachable servers"
	... Error value is nil
	
	----------------------------------------------------------------------
	OOPS: 231 passed, 19 skipped, 12 FAILED
	--- FAIL: TestAll (517.10s)

**Comment by domodwyer** [comment]
Hi @rogpeppe,

I can't even get the tests to run locally (macOS) - the test harness is a bit of a nightmare, and on top of that tests randomly fail.

Personally I unit test my code changes (mocking out Mongo) where possible and then write integration tests that run on travis when I push the feature branch - these also randomly fail all the time and have to be restarted...

The existing test setup is a bit of a mess!

Dom
