### ISSUE TITLE
Migrating from go-mgo 

### ISSUE THREAD

**Issue by dharnnie** [globalsign/mgo#86]
Hi,

Please is there a documentation for this on godoc?

Does this project build on top of go-mgo by Gustavo Niemier?

**Comment by domodwyer** [comment]
Hi @dharnnie 

The godoc page is [here](https://godoc.org/github.com/globalsign/mgo) and this package is fully backwards compatible with go-mgo - you should just be able to change the imports and be good to go!

Good luck!
Dom
