### ISSUE TITLE
Pipe (aggregate) options

### ISSUE THREAD

**Issue by ganigeorgiev** [globalsign/mgo#93]
Is there a way to define [aggreate options](https://docs.mongodb.com/manual/reference/method/db.collection.aggregate/) (and more precisely **collation**) by using `.Pipe()`? Currently only `AllowDisk` seems to be available.

**Comment by domodwyer** [comment]
Hi @ganigeorgiev 

I believe the `Pipe()` method supports all aggregations I know of - at least the [documentation](https://godoc.org/github.com/globalsign/mgo#Collection.Pipe) seems to suggest as much?

If you have any problems post back here and we'll look into it - perhaps include an example of the MongoDB query you're trying to run.

Dom

**Comment by ganigeorgiev** [comment]
@domodwyer This is only the pipeline argument. What I mean was options like "explain", "maxTimeMS", "bypassDocumentValidation", "collation", etc (check the second argument of [mongo aggregate](https://docs.mongodb.com/manual/reference/method/db.collection.aggregate/)).

**Comment by domodwyer** [comment]
Ah sorry, I see what you mean now.

We don't use aggregations so I'm not too familiar with it but it looks like you're right - there's no obvious way to configure the timeout, etc. If you wind up adding this functionality, please do open a PR!

Dom

**Comment by peterdeka** [comment]
Yep this should also address some options for the `ChangeStreams` (`MaxAwaitTimeMS` and `Collation`)
