### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by djensen47** [globalsign/mgo#94]
Now that this repo is the new source of truth for mgo development, Will there be a dedicated site for non-godoc documentation? Something like http://labix.org/mgo but up to date with this repo?

Thanks for all the great work and continuing development on this library!

**Comment by domodwyer** [comment]
Hi @djensen47 - really sorry about the lack of a reply, I've been away at a conference for the last few days.

There's currently no plans for an accompanying site, it will add maintenance cost - personally I never looked at it! Is there something specific you used to rely on the labix site for? Perhaps we can find a way to work it in.

Dom

**Comment by cyberhck** [comment]
I believe we should have some documentation on readme, godoc etc. use cases, and stuffs. Right now this looks so empty.

**Comment by djensen47** [comment]
It was useful for setup and usually a docs page is more straightforward than a giant godoc page. Honestly, documentation is a necessity of maintaining any open source project. It doesn't _have_ to be a separate site you at least a README and a godoc.

**Comment by domodwyer** [comment]
I can see your point! Saying that, as an open source project we'll happily look at PRs improving the docs 👍 

We've added a couple of [code examples](https://godoc.org/github.com/globalsign/mgo#pkg-examples) on the GoDoc page but it could definitely be expanded - it's preferred to use GoDoc as it's checked within the test suite - if a PR would cause the example code to become out of sync with the examples (say, in the README) this would cause a build error and would prevent a merge.

This fork was originally performance & bug fix driven - it was expected users already used mgo and were looking for a drop-in replacement, hence the light README as there was very little to say - again, we'll happily review PRs changing this!

Thanks,
Dom

**Comment by djensen47** [comment]
Is there another issue that's tracking documentation?

Right now, if you came to this library fresh, without the http://labix.org/mgo docs, you would not know how to Insert data nor get data out using a struct. Nor is there any clue that you can use a map (or not for that matter) instead of a struct.

**Comment by domodwyer** [comment]
Hi @djensen47 

There's no plans to add an accompanying site / spreading the documentation over several sources - it only makes it trickier for newcomers to find what they're looking for and more work to keep it all in sync. Go strongly encourages documentation within your code which is automatically available on godoc which makes it the go-to place for everyone.

The basic insert/read operations you describe can easily be covered by adding examples [to the code](https://github.com/globalsign/mgo/blob/master/example_test.go) where everyone with a copy of the repo can access them, even offline.

We'll happily accept a PR to improve documentation on godoc in general, or maybe a quick-start markdown file within this repo though it would have to provide significant value to justify having documentation outside the official godoc documentation.

Dom

**Comment by djensen47** [comment]
So regarding _Godoc_ doc bugs, should I file them individually, open for discussion, then submit a PR? Or do you have another approach in mind?

**Comment by domodwyer** [comment]
Hi @djensen47 

There's nothing tracking documentation at the moment, but feel free to open issues for specific things that you feel would benefit being included - we'll happily accept PRs for any improvements to the docs.

Regarding the example file, it's [rendered](https://godoc.org/github.com/globalsign/mgo#pkg-examples) in GoDoc, you don't have to go looking for the file so sticks with the "all in code" idea.

Dom
