### ISSUE TITLE
Consider publishing through gopkg.in?

### ISSUE THREAD

**Issue by kevinguard** [globalsign/mgo#95]
Is there any reason why we haven't published this through `gopkg.in`? I'd make all API and documentations gathered in just one place while letting Gopkg manifests cleaner and less verbos.

**Comment by domodwyer** [comment]
Hi @kevinguard 

I'm weary of using `gopkg.in` - it's maintained by the original mgo author and the mgo project was abandoned for a long time - I'd hate to see the same happen to `gopkg.in` and I'm not suggesting it will happen, but it's a risk for little reward. 

The documentation is linked to from the README and we tag all releases to allow users to pin dependencies with a readable name. Is there something you'd like to see that `gopkg.in` provides?

Dom

**Comment by niemeyer** [comment]
@domodwyer Please don't extrapolate my lack of time to make changes in mgo into a strange territory. The mgo code never stopped working. In fact, it was good enough that you decided to use it, I think?

You are welcome.

**Comment by domodwyer** [comment]
@niemeyer I'm not having a dig - we're all very grateful for the time and effort that has gone into both mgo and gopkg.in - my comment was simply explaining there's little benefit for the added risk of relying on a 3rd party, regardless of whom that is.

Dom

**Comment by niemeyer** [comment]
No that was not your point, actually. There's a a direct reference to me personally.

You're welcome, Dom.

**Comment by kevinguard** [comment]
@domodwyer Appreciate your comment and thoughts. Totally agree! Thanks for keeping this repo great! Cheers!
