### ISSUE TITLE
Embedded Mongo for Integration tests

### ISSUE THREAD

**Issue by akhettar** [globalsign/mgo#96]
Hi
I am a new to GO and its ecosystem. I was wondering if there is a way to run an embedded Mongo for integration test. I am aware of the **globalsign/mgo/dbtest**. I have configured an init_test.go to run the server prior to running my integration test. Unfortunately, the Mongo server that gets started by the **dbserver.go** runs on a random port and there is no way to communicate that port into the integration test.
Any directions would really be appreciated. Apologies if this kind of questions are not meant teo be published here, any forum or channel where we can post these kind of questions?
thanks in advance.
Ayache

**Comment by akhettar** [comment]
Hi
I have found the following post which answers my above question: https://medium.com/@mvmaasakkers/writing-integration-tests-with-mongodb-support-231580a566cd. I had to install **gopkg.in/tomb.v2** which this project doesn't seem to have it as a dependency.

Regards

Ayache

**Comment by domodwyer** [comment]
Hi @akhettar 

I didn't actually know about the trick in that article, thanks!

We took a slightly different approach: we run integration tests by setting an environment variable defining the hostname (`MONGO_TEST_HOST="mongo://something"`) and use a randomised database name prefix (`MONGO_TEST_DB="<build number>"`) to avoid collisions with concurrent builds.

Either way, hope you're sorted!

Dom
